==1219== Memcheck, a memory error detector
==1219== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==1219== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info
==1219== Command: ./bin/utest
==1219== 
===============================================================================
All tests passed (5 assertions in 1 test case)

==1219== 
==1219== HEAP SUMMARY:
==1219==     in use at exit: 826 bytes in 5 blocks
==1219==   total heap usage: 1,772 allocs, 1,767 frees, 327,790 bytes allocated
==1219== 
==1219== 10 bytes in 1 blocks are definitely lost in loss record 1 of 5
==1219==    at 0x4C2BBAF: malloc (vg_replace_malloc.c:299)
==1219==    by 0x2F144B: ____C_A_T_C_H____T_E_S_T____0() (PipeAndFifoTest.cc:35)
==1219==    by 0x268315: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1219==    by 0x267A78: Catch::TestCase::invoke() const (catch.hpp:10232)
==1219==    by 0x262B50: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1219==    by 0x2628AA: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:9078)
==1219==    by 0x2615AC: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:8861)
==1219==    by 0x263E72: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (catch.hpp:9394)
==1219==    by 0x2650B9: Catch::Session::runInternal() (catch.hpp:9592)
==1219==    by 0x264E8E: Catch::Session::run() (catch.hpp:9549)
==1219==    by 0x264E2E: Catch::Session::run(int, char**) (catch.hpp:9517)
==1219==    by 0x2781E4: main (test.cc:16)
==1219== 
==1219== 64 bytes in 1 blocks are indirectly lost in loss record 2 of 5
==1219==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1219==    by 0x2F59C7: __gnu_cxx::new_allocator<ndsl::net::PipeAndFifo::SInfo**>::allocate(unsigned long, void const*) (new_allocator.h:104)
==1219==    by 0x2F55CA: std::allocator_traits<std::allocator<ndsl::net::PipeAndFifo::SInfo**> >::allocate(std::allocator<ndsl::net::PipeAndFifo::SInfo**>&, unsigned long) (alloc_traits.h:436)
==1219==    by 0x2F52CA: std::_Deque_base<ndsl::net::PipeAndFifo::SInfo*, std::allocator<ndsl::net::PipeAndFifo::SInfo*> >::_M_allocate_map(unsigned long) (stl_deque.h:614)
==1219==    by 0x2F4E68: std::_Deque_base<ndsl::net::PipeAndFifo::SInfo*, std::allocator<ndsl::net::PipeAndFifo::SInfo*> >::_M_initialize_map(unsigned long) (stl_deque.h:687)
==1219==    by 0x2F4AE8: std::_Deque_base<ndsl::net::PipeAndFifo::SInfo*, std::allocator<ndsl::net::PipeAndFifo::SInfo*> >::_Deque_base() (stl_deque.h:490)
==1219==    by 0x2F497B: std::deque<ndsl::net::PipeAndFifo::SInfo*, std::allocator<ndsl::net::PipeAndFifo::SInfo*> >::deque() (stl_deque.h:884)
==1219==    by 0x2F3C95: ndsl::net::PipeAndFifo::PipeAndFifo(ndsl::net::EventLoop*) (PipeAndFifo.cc:30)
==1219==    by 0x2F12E1: ____C_A_T_C_H____T_E_S_T____0() (PipeAndFifoTest.cc:31)
==1219==    by 0x268315: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1219==    by 0x267A78: Catch::TestCase::invoke() const (catch.hpp:10232)
==1219==    by 0x262B50: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1219== 
==1219== 72 bytes in 1 blocks are indirectly lost in loss record 3 of 5
==1219==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1219==    by 0x2F3E03: ndsl::net::PipeAndFifo::createPipe(int*) (PipeAndFifo.cc:60)
==1219==    by 0x2F1394: ____C_A_T_C_H____T_E_S_T____0() (PipeAndFifoTest.cc:32)
==1219==    by 0x268315: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1219==    by 0x267A78: Catch::TestCase::invoke() const (catch.hpp:10232)
==1219==    by 0x262B50: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1219==    by 0x2628AA: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:9078)
==1219==    by 0x2615AC: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:8861)
==1219==    by 0x263E72: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (catch.hpp:9394)
==1219==    by 0x2650B9: Catch::Session::runInternal() (catch.hpp:9592)
==1219==    by 0x264E8E: Catch::Session::run() (catch.hpp:9549)
==1219==    by 0x264E2E: Catch::Session::run(int, char**) (catch.hpp:9517)
==1219== 
==1219== 512 bytes in 1 blocks are indirectly lost in loss record 4 of 5
==1219==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1219==    by 0x2F5BF9: __gnu_cxx::new_allocator<ndsl::net::PipeAndFifo::SInfo*>::allocate(unsigned long, void const*) (new_allocator.h:104)
==1219==    by 0x2F5984: std::allocator_traits<std::allocator<ndsl::net::PipeAndFifo::SInfo*> >::allocate(std::allocator<ndsl::net::PipeAndFifo::SInfo*>&, unsigned long) (alloc_traits.h:436)
==1219==    by 0x2F5575: std::_Deque_base<ndsl::net::PipeAndFifo::SInfo*, std::allocator<ndsl::net::PipeAndFifo::SInfo*> >::_M_allocate_node() (stl_deque.h:600)
==1219==    by 0x2F5315: std::_Deque_base<ndsl::net::PipeAndFifo::SInfo*, std::allocator<ndsl::net::PipeAndFifo::SInfo*> >::_M_create_nodes(ndsl::net::PipeAndFifo::SInfo***, ndsl::net::PipeAndFifo::SInfo***) (stl_deque.h:725)
==1219==    by 0x2F4EC1: std::_Deque_base<ndsl::net::PipeAndFifo::SInfo*, std::allocator<ndsl::net::PipeAndFifo::SInfo*> >::_M_initialize_map(unsigned long) (stl_deque.h:699)
==1219==    by 0x2F4AE8: std::_Deque_base<ndsl::net::PipeAndFifo::SInfo*, std::allocator<ndsl::net::PipeAndFifo::SInfo*> >::_Deque_base() (stl_deque.h:490)
==1219==    by 0x2F497B: std::deque<ndsl::net::PipeAndFifo::SInfo*, std::allocator<ndsl::net::PipeAndFifo::SInfo*> >::deque() (stl_deque.h:884)
==1219==    by 0x2F3C95: ndsl::net::PipeAndFifo::PipeAndFifo(ndsl::net::EventLoop*) (PipeAndFifo.cc:30)
==1219==    by 0x2F12E1: ____C_A_T_C_H____T_E_S_T____0() (PipeAndFifoTest.cc:31)
==1219==    by 0x268315: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1219==    by 0x267A78: Catch::TestCase::invoke() const (catch.hpp:10232)
==1219== 
==1219== 816 (168 direct, 648 indirect) bytes in 1 blocks are definitely lost in loss record 5 of 5
==1219==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1219==    by 0x2F12CC: ____C_A_T_C_H____T_E_S_T____0() (PipeAndFifoTest.cc:31)
==1219==    by 0x268315: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1219==    by 0x267A78: Catch::TestCase::invoke() const (catch.hpp:10232)
==1219==    by 0x262B50: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1219==    by 0x2628AA: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:9078)
==1219==    by 0x2615AC: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:8861)
==1219==    by 0x263E72: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (catch.hpp:9394)
==1219==    by 0x2650B9: Catch::Session::runInternal() (catch.hpp:9592)
==1219==    by 0x264E8E: Catch::Session::run() (catch.hpp:9549)
==1219==    by 0x264E2E: Catch::Session::run(int, char**) (catch.hpp:9517)
==1219==    by 0x2781E4: main (test.cc:16)
==1219== 
==1219== LEAK SUMMARY:
==1219==    definitely lost: 178 bytes in 2 blocks
==1219==    indirectly lost: 648 bytes in 3 blocks
==1219==      possibly lost: 0 bytes in 0 blocks
==1219==    still reachable: 0 bytes in 0 blocks
==1219==         suppressed: 0 bytes in 0 blocks
==1219== 
==1219== For counts of detected and suppressed errors, rerun with: -v
==1219== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
